local M = {}

local function get_base_colors(colors, contrast)
  local bg = vim.o.background
  local base_colors = {
    -- options (dark mode by default)
    bg0 = colors.dark0,
    bg1 = colors.dark1,
    bg2 = colors.dark2,
    bg3 = colors.dark3,
    bg4 = colors.dark4,
    fg0 = colors.light0,
    fg1 = colors.light1,
    fg2 = colors.light2,
    fg3 = colors.light3,
    fg4 = colors.light4,
    red = colors.bright_red,
    green = colors.bright_green,
    yellow = colors.bright_yellow,
    blue = colors.bright_blue,
    purple = colors.bright_purple,
    aqua = colors.bright_aqua,
    orange = colors.bright_orange,
    neutral_red = colors.neutral_red,
    neutral_green = colors.neutral_green,
    neutral_yellow = colors.neutral_yellow,
    neutral_blue = colors.neutral_blue,
    neutral_purple = colors.neutral_purple,
    neutral_aqua = colors.neutral_aqua,
  }

  local light_colors = {
    bg0 = colors.light0,
    bg1 = colors.light1,
    bg2 = colors.light2,
    bg3 = colors.light3,
    bg4 = colors.light4,
    fg0 = colors.dark0,
    fg1 = colors.dark1,
    fg2 = colors.dark2,
    fg3 = colors.dark3,
    fg4 = colors.dark4,
    red = colors.faded_red,
    green = colors.faded_green,
    yellow = colors.faded_yellow,
    blue = colors.faded_blue,
    purple = colors.faded_purple,
    aqua = colors.faded_aqua,
    orange = colors.faded_orange,
    neutral_red = colors.neutral_red,
    neutral_green = colors.neutral_green,
    neutral_yellow = colors.neutral_yellow,
    neutral_blue = colors.neutral_blue,
    neutral_purple = colors.neutral_purple,
    neutral_aqua = colors.neutral_aqua,
  }

  -- swap colors if light mode
  if bg == "light" then
    base_colors = light_colors
  end

  if contrast == "hard" then
    base_colors.bg0 = colors[bg .. "0_hard"]
  elseif contrast == "soft" then
    base_colors.bg0 = colors[bg .. "0_soft"]
  end

  base_colors.gray = colors.gray

  return base_colors
end

-- neovim terminal mode colors
local function set_terminal_colors(colors)
  vim.g.terminal_color_0 = colors.bg0
  vim.g.terminal_color_8 = colors.gray
  vim.g.terminal_color_1 = colors.neutral_red
  vim.g.terminal_color_9 = colors.red
  vim.g.terminal_color_2 = colors.neutral_green
  vim.g.terminal_color_10 = colors.green
  vim.g.terminal_color_3 = colors.neutral_yellow
  vim.g.terminal_color_11 = colors.yellow
  vim.g.terminal_color_4 = colors.neutral_blue
  vim.g.terminal_color_12 = colors.blue
  vim.g.terminal_color_5 = colors.neutral_purple
  vim.g.terminal_color_13 = colors.purple
  vim.g.terminal_color_6 = colors.neutral_aqua
  vim.g.terminal_color_14 = colors.aqua
  vim.g.terminal_color_7 = colors.fg4
  vim.g.terminal_color_15 = colors.fg1
end

M.setup = function()
  local config = require("gruvbox").config
  local palette = require("gruvbox.palette")
  local colors = get_base_colors(palette, config.contrast)

  set_terminal_colors(colors)

  local groups = {
    -- Base groups
    GruvboxFg0 = { fg = colors.fg0 },
    GruvboxFg1 = { fg = colors.fg1 },
    GruvboxFg2 = { fg = colors.fg2 },
    GruvboxFg3 = { fg = colors.fg3 },
    GruvboxFg4 = { fg = colors.fg4 },
    GruvboxGray = { fg = colors.gray },
    GruvboxBg0 = { fg = colors.bg0 },
    GruvboxBg1 = { fg = colors.bg1 },
    GruvboxBg2 = { fg = colors.bg2 },
    GruvboxBg3 = { fg = colors.bg3 },
    GruvboxBg4 = { fg = colors.bg4 },
    GruvboxRed = { fg = colors.red },
    GruvboxRedBold = { fg = colors.red, bold = config.bold },
    GruvboxGreen = { fg = colors.green },
    GruvboxGreenBold = { fg = colors.green, bold = config.bold },
    GruvboxYellow = { fg = colors.yellow },
    GruvboxYellowBold = { fg = colors.yellow, bold = config.bold },
    GruvboxBlue = { fg = colors.blue },
    GruvboxBlueBold = { fg = colors.blue, bold = config.bold },
    GruvboxPurple = { fg = colors.purple },
    GruvboxPurpleBold = { fg = colors.purple, bold = config.bold },
    GruvboxAqua = { fg = colors.aqua },
    GruvboxAquaBold = { fg = colors.aqua, bold = config.bold },
    GruvboxOrange = { fg = colors.orange },
    GruvboxOrangeBold = { fg = colors.orange, bold = config.bold },
    GruvboxRedSign = { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxGreenSign = { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxYellowSign = { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxBlueSign = { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxPurpleSign = { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxAquaSign = { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxOrangeSign = { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    GruvboxGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    GruvboxYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    GruvboxBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    GruvboxPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    GruvboxAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    GruvboxOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    Cursor = { reverse = config.inverse },
    lCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    vCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    Directory = { link = "GruvboxGreenBold" },
    DiffAdd = { fg = colors.green, bg = colors.bg0, reverse = config.inverse },
    DiffChange = { fg = colors.aqua, bg = colors.bg0, reverse = config.inverse },
    DiffDelete = { fg = colors.red, bg = colors.bg0, reverse = config.inverse },
    DiffText = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    VertSplit = { fg = colors.bg3, bg = colors.bg0 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic },
    FoldColumn = { fg = colors.gray, bg = colors.bg1 },
    SignColumn = { bg = colors.bg1 },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    LineNr = { fg = colors.bg4 },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ModeMsg = { link = "GruvboxYellowBold" },
    MoreMsg = { link = "GruvboxYellowBold" },
    NonText = { link = "GruvboxBg2" },
    Normal = { fg = colors.fg1, bg = colors.bg0 },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    Question = { link = "GruvboxOrangeBold" },
    QuickFixLine = { bg = colors.bg0, bold = config.bold },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    SpecialKey = { link = "GruvboxFg4" },
    SpellRare = { link = "GruvboxPurpleUnderline" },
    SpellBad = { link = "GruvboxRedUnderline" },
    SpellLocal = { link = "GruvboxAquaUnderline" },
    SpellCap = { link = "GruvboxBlueUnderline" },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    Title = { link = "GruvboxGreenBold" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    WarningMsg = { link = "GruvboxRedBold" },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Constant = { link = "GruvboxPurple" },
    Special = { link = "GruvboxOrange" },
    String = { fg = colors.green, italic = config.italic },
    Character = { link = "GruvboxPurple" },
    Number = { link = "GruvboxPurple" },
    Boolean = { link = "GruvboxPurple" },
    Float = { link = "GruvboxPurple" },
    Identifier = { link = "GruvboxBlue" },
    Function = { link = "GruvboxGreenBold" },
    Statement = { link = "GruvboxRed" },
    Conditional = { link = "GruvboxRed" },
    Repeat = { link = "GruvboxRed" },
    Label = { link = "GruvboxRed" },
    Exception = { link = "GruvboxRed" },
    Keyword = { link = "GruvboxRed" },
    Operator = { link = "GruvboxFg1" },
    PreProc = { link = "GruvboxAqua" },
    Include = { link = "GruvboxAqua" },
    Define = { link = "GruvboxAqua" },
    Macro = { link = "GruvboxAqua" },
    PreCondit = { link = "GruvboxAqua" },
    Type = { link = "GruvboxYellow" },
    StorageClass = { link = "GruvboxOrange" },
    Structure = { link = "GruvboxAqua" },
    Typedef = { link = "GruvboxYellow" },
    SpecialChar = { link = "GruvboxRed" },
    Tag = { link = "GruvboxAquaBold" },
    Delimiter = { link = "GruvboxFg3" },
    Comment = { fg = colors.gray, italic = config.italic },
    Debug = { link = "GruvboxRed" },
    Underlined = { fg = colors.blue, underline = config.underline },
    Bold = { bold = config.bold },
    Italic = { italic = config.italic },
    Ignore = {},
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Todo = { fg = colors.fg0, bold = config.bold, italic = config.italic },
    diffAdded = { link = "GruvboxGreen" },
    diffRemoved = { link = "GruvboxRed" },
    diffChanged = { link = "GruvboxAqua" },
    diffFile = { link = "GruvboxOrange" },
    diffNewFile = { link = "GruvboxYellow" },
    diffLine = { link = "GruvboxBlue" },
    -- signature
    SignatureMarkText = { link = "GruvboxBlueSign" },
    SignatureMarkerText = { link = "GruvboxPurpleSign" },
    -- gitcommit
    gitcommitSelectedFile = { link = "GruvboxGreen" },
    gitcommitDiscardedFile = { link = "GruvboxRed" },
    -- checkhealth
    healthError = { fg = colors.bg0, bg = colors.red },
    healthSuccess = { fg = colors.bg0, bg = colors.green },
    healthWarning = { fg = colors.bg0, bg = colors.yellow },
    -- xml
    xmlTag = { link = "GruvboxAquaBold" },
    xmlEndTag = { link = "GruvboxAquaBold" },
    xmlTagName = { link = "GruvboxBlue" },
    xmlEqual = { link = "GruvboxBlue" },
    docbkKeyword = { link = "GruvboxAquaBold" },
    xmlDocTypeDecl = { link = "GruvboxGray" },
    xmlDocTypeKeyword = { link = "GruvboxPurple" },
    xmlCdataStart = { link = "GruvboxGray" },
    xmlCdataCdata = { link = "GruvboxPurple" },
    dtdFunction = { link = "GruvboxGray" },
    dtdTagName = { link = "GruvboxPurple" },
    xmlAttrib = { link = "GruvboxOrange" },
    xmlProcessingDelim = { link = "GruvboxGray" },
    dtdParamEntityPunct = { link = "GruvboxGray" },
    dtdParamEntityDPunct = { link = "GruvboxGray" },
    xmlAttribPunct = { link = "GruvboxGray" },
    xmlEntity = { link = "GruvboxRed" },
    xmlEntityPunct = { link = "GruvboxRed" },
    -- purescript
    purescriptModuleKeyword = { link = "GruvboxAqua" },
    purescriptModuleName = { link = "GruvboxFg1" },
    purescriptWhere = { link = "GruvboxAqua" },
    purescriptDelimiter = { link = "GruvboxFg4" },
    purescriptType = { link = "GruvboxFg1" },
    purescriptImportKeyword = { link = "GruvboxAqua" },
    purescriptHidingKeyword = { link = "GruvboxAqua" },
    purescriptAsKeyword = { link = "GruvboxAqua" },
    purescriptStructure = { link = "GruvboxAqua" },
    purescriptOperator = { link = "GruvboxBlue" },
    purescriptTypeVar = { link = "GruvboxFg1" },
    purescriptConstructor = { link = "GruvboxFg1" },
    purescriptFunction = { link = "GruvboxFg1" },
    purescriptConditional = { link = "GruvboxOrange" },
    purescriptBacktick = { link = "GruvboxOrange" },
    -- coffescript
    coffeeExtendedOp = { link = "GruvboxFg3" },
    coffeeSpecialOp = { link = "GruvboxFg3" },
    coffeeCurly = { link = "GruvboxOrange" },
    coffeeParen = { link = "GruvboxFg3" },
    coffeeBracket = { link = "GruvboxOrange" },
    -- objc
    objcTypeModifier = { link = "GruvboxRed" },
    objcDirective = { link = "GruvboxBlue" },
    -- moonscript
    moonSpecialOp = { link = "GruvboxFg3" },
    moonExtendedOp = { link = "GruvboxFg3" },
    moonFunction = { link = "GruvboxFg3" },
    moonObject = { link = "GruvboxYellow" },
    -- elixir
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "GruvboxGreen" },
    elixirInterpolationDelimiter = { link = "GruvboxAqua" },
    elixirModuleDeclaration = { link = "GruvboxYellow" },
    -- markdown
    markdownItalic = { fg = colors.fg3, bold = config.italic },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = config.italic },
    markdownH1 = { link = "GruvboxGreenBold" },
    markdownH2 = { link = "markdownH1" },
    markdownH3 = { link = "GruvboxYellowBold" },
    markdownH4 = { link = "markdownH3" },
    markdownH5 = { link = "GruvboxYellow" },
    markdownH6 = { link = "markdownH5" },
    markdownCode = { link = "GruvboxAqua" },
    markdownCodeBlock = { link = "GruvboxAqua" },
    markdownCodeDelimiter = { link = "GruvboxAqua" },
    markdownBlockquote = { link = "GruvboxGray" },
    markdownListMarker = { link = "GruvboxGray" },
    markdownOrderedListMarker = { link = "GruvboxGray" },
    markdownRule = { link = "GruvboxGray" },
    markdownHeadingRule = { link = "GruvboxGray" },
    markdownUrlDelimiter = { link = "GruvboxFg3" },
    markdownLinkDelimiter = { link = "GruvboxFg3" },
    markdownLinkTextDelimiter = { link = "GruvboxFg3" },
    markdownHeadingDelimiter = { link = "GruvboxOrange" },
    markdownUrl = { link = "GruvboxPurple" },
    markdownUrlTitleDelimiter = { link = "GruvboxGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    -- haskell
    haskellType = { link = "GruvboxBlue" },
    haskellIdentifier = { link = "GruvboxAqua" },
    haskellSeparator = { link = "GruvboxFg4" },
    haskellDelimiter = { link = "GruvboxOrange" },
    haskellOperators = { link = "GruvboxPurple" },
    haskellBacktick = { link = "GruvboxOrange" },
    haskellStatement = { link = "GruvboxPurple" },
    haskellConditional = { link = "GruvboxPurple" },
    haskellLet = { link = "GruvboxRed" },
    haskellDefault = { link = "GruvboxRed" },
    haskellWhere = { link = "GruvboxRed" },
    haskellBottom = { link = "GruvboxRedBold" },
    haskellImportKeywords = { link = "GruvboxPurpleBold" },
    haskellDeclKeyword = { link = "GruvboxOrange" },
    haskellDecl = { link = "GruvboxOrange" },
    haskellDeriving = { link = "GruvboxPurple" },
    haskellAssocType = { link = "GruvboxAqua" },
    haskellNumber = { link = "GruvboxAqua" },
    haskellPragma = { link = "GruvboxRedBold" },
    haskellTH = { link = "GruvboxAquaBold" },
    haskellForeignKeywords = { link = "GruvboxGreen" },
    haskellKeyword = { link = "GruvboxRed" },
    haskellFloat = { link = "GruvboxAqua" },
    haskellInfix = { link = "GruvboxPurple" },
    haskellQuote = { link = "GruvboxGreenBold" },
    haskellShebang = { link = "GruvboxYellowBold" },
    haskellLiquid = { link = "GruvboxPurpleBold" },
    haskellQuasiQuoted = { link = "GruvboxBlueBold" },
    haskellRecursiveDo = { link = "GruvboxPurple" },
    haskellQuotedType = { link = "GruvboxRed" },
    haskellPreProc = { link = "GruvboxFg4" },
    haskellTypeRoles = { link = "GruvboxRedBold" },
    haskellTypeForall = { link = "GruvboxRed" },
    haskellPatternKeyword = { link = "GruvboxBlue" },
    -- html
    htmlTag = { link = "GruvboxAquaBold" },
    htmlEndTag = { link = "GruvboxAquaBold" },
    htmlTagName = { link = "GruvboxBlue" },
    htmlArg = { link = "GruvboxOrange" },
    htmlTagN = { link = "GruvboxFg1" },
    htmlSpecialTagName = { link = "GruvboxBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "GruvboxRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = config.italic },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = config.italic,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = config.italic,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.italic },
    -- netrw
    netrwDir = { link = "GruvboxAqua" },
    netrwClassify = { link = "GruvboxAqua" },
    netrwLink = { link = "GruvboxGray" },
    netrwSymLink = { link = "GruvboxFg1" },
    netrwExe = { link = "GruvboxYellow" },
    netrwComment = { link = "GruvboxGray" },
    netrwList = { link = "GruvboxBlue" },
    netrwHelpCmd = { link = "GruvboxAqua" },
    netrwCmdSep = { link = "GruvboxFg3" },
    netrwVersion = { link = "GruvboxGreen" },
    -- nvim-treesitter
    TSNone = {},
    TSError = {},
    TSTitle = { link = "Title" },
    TSLiteral = { link = "String" },
    TSURI = { link = "Underlined" },
    TSVariable = { link = "GruvboxFg1" },
    TSPunctDelimiter = { link = "Delimiter" },
    TSPunctBracket = { link = "Delimiter" },
    TSPunctSpecial = { link = "Delimiter" },
    TSConstant = { link = "Constant" },
    TSConstBuiltin = { link = "Special" },
    TSConstMacro = { link = "Define" },
    TSString = { link = "String" },
    TSStringRegex = { link = "String" },
    TSStringEscape = { link = "SpecialChar" },
    TSCharacter = { link = "Character" },
    TSNumber = { link = "Number" },
    TSBoolean = { link = "Boolean" },
    TSFloat = { link = "Float" },
    TSFunction = { link = "Function" },
    TSFuncBuiltin = { link = "Special" },
    TSFuncMacro = { link = "Macro" },
    TSParameter = { link = "Identifier" },
    TSParameterReference = { link = "TSParameter" },
    TSMethod = { link = "Function" },
    TSField = { link = "Identifier" },
    TSProperty = { link = "Identifier" },
    TSConstructor = { link = "Special" },
    TSAnnotation = { link = "PreProc" },
    TSAttribute = { link = "PreProc" },
    TSNamespace = { link = "Include" },
    TSConditional = { link = "Conditional" },
    TSRepeat = { link = "Repeat" },
    TSLabel = { link = "Label" },
    TSOperator = { link = "Operator" },
    TSKeyword = { link = "Keyword" },
    TSKeywordFunction = { link = "Keyword" },
    TSKeywordOperator = { link = "GruvboxRed" },
    TSException = { link = "Exception" },
    TSType = { link = "Type" },
    TSTypeBuiltin = { link = "Type" },
    TSInclude = { link = "Include" },
    TSVariableBuiltin = { link = "Special" },
    TSText = { link = "TSNone" },
    TSStrong = { bold = config.bold },
    TSEmphasis = { italic = config.italic },
    TSUnderline = { underline = config.underline },
    TSComment = { link = "Comment" },
    TSStructure = { link = "GruvboxOrange" },
    TSTag = { link = "GruvboxOrange" },
    TSTagDelimiter = { link = "GruvboxGreen" },
    -- telescope.nvim
    TelescopeSelection = { link = "GruvboxOrangeBold" },
    TelescopeSlectionCaret = { link = "GruvboxRed" },
    TelescopeMultiSelection = { link = "GruvboxGray" },
    TelescopeNormal = { link = "GruvboxFg1" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "GruvboxBlue" },
    TelescopePromptPrefix = { link = "GruvboxRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    -- lspsaga.nvim
    LspSagaDiagnosticBorder = { link = "NormalNC" },
    LspSagaDiagnosticHeader = { link = "GruvboxRed" },
    LspSagaDiagnosticTruncateLine = { link = "NormalNC" },
    LspFloatWinBorder = { link = "NormalNC" },
    LspSagaBorderTitle = { link = "Title" },
    TargetWord = { link = "Error" },
    ReferencesCount = { link = "Title" },
    ReferencesIcon = { link = "Special" },
    DefinitionCount = { link = "Title" },
    TargetFileName = { link = "Comment" },
    DefinitionIcon = { link = "Special" },
    ProviderTruncateLine = { link = "NormalNC" },
    SagaShadow = { link = "GruvboxBg0" },
    LspSagaFinderSelection = { link = "Search" },
    DiagnosticTruncateLine = { link = "NormalNC" },
    DiagnosticWarning = { link = "DiagnosticWarn" },
    DiagnosticInformation = { link = "DiagnosticInfo" },
    DefinitionPreviewTitle = { link = "Title" },
    LspSagaShTruncateLine = { link = "NormalNC" },
    LspSagaDocTruncateLine = { link = "NormalNC" },
    LineDiagTuncateLine = { link = "NormalNC" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionTruncateLine = { link = "NormalNC" },
    LspSagaCodeActionContent = { link = "Normal" },
    LspSagaRenamePromptPrefix = { link = "GruvboxFg2" },
    LspSagaRenameBorder = { bold = config.bold },
    LspSagaHoverBorder = { bold = config.bold },
    LspSagaSignatureHelpBorder = { bold = config.bold },
    LspSagaCodeActionBorder = { bold = config.bold },
    LspSagaAutoPreview = {},
    LspSagaDefPreviewBorder = { bold = config.bold },
    LspLinesDiagBorder = { bold = config.bold },
    -- vim-startify
    StartifyBracket = { link = "GruvboxFg3" },
    StartifyFile = { link = "GruvboxFg1" },
    StartifyNumber = { link = "GruvboxBlue" },
    StartifyPath = { link = "GruvboxGray" },
    StartifySlash = { link = "GruvboxGray" },
    StartifySection = { link = "GruvboxYellow" },
    StartifySpecial = { link = "GruvboxBg2" },
    StartifyHeader = { link = "GruvboxOrange" },
    StartifyFooter = { link = "GruvboxBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    -- vim-signify
    SignifySignAdd = { link = "GruvboxGreenSign" },
    SignifySignChange = { link = "GruvboxAquaSign" },
    SignifySignDelete = { link = "GruvboxRedSign" },
    -- syntastic
    SyntasticError = { link = "GruvboxRedUnderline" },
    SyntasticWarning = { link = "GruvboxYellowUnderline" },
    SyntasticErrorSign = { link = "GruvboxRedSign" },
    SyntasticWarningSign = { link = "GruvboxYellowSign" },
    -- termdebug
    debugPC = { bg = colors.faded_blue },
    debugBreakpoint = { link = "GruvboxRedSign" },
    -- vim-dirvish
    DirvishPathTail = { link = "GruvboxAqua" },
    DirvishArg = { link = "GruvboxYellow" },
    -- nerdtree
    NERDTreeDir = { link = "GruvboxAqua" },
    NERDTreeDirSlash = { link = "GruvboxAqua" },
    NERDTreeOpenable = { link = "GruvboxOrange" },
    NERDTreeClosable = { link = "GruvboxOrange" },
    NERDTreeFile = { link = "GruvboxFg1" },
    NERDTreeExecFile = { link = "GruvboxYellow" },
    NERDTreeUp = { link = "GruvboxGray" },
    NERDTreeCWD = { link = "GruvboxGreen" },
    NERDTreeHelp = { link = "GruvboxFg1" },
    NERDTreeToggleOn = { link = "GruvboxGreen" },
    NERDTreeToggleOff = { link = "GruvboxRed" },
    -- coc.nvim
    CocErrorSign = { link = "GruvboxRedSign" },
    CocWarningSign = { link = "GruvboxOrangeSign" },
    CocInfoSign = { link = "GruvboxBlueSign" },
    CocHintSign = { link = "GruvboxAquaSign" },
    CocErrorFloat = { link = "GruvboxRed" },
    CocWarningFloat = { link = "GruvboxOrange" },
    CocInfoFloat = { link = "GruvboxBlue" },
    CocHintFloat = { link = "GruvboxAqua" },
    CocDiagnosticsError = { link = "GruvboxRed" },
    CocDiagnosticsWarning = { link = "GruvboxOrange" },
    CocDiagnosticsInfo = { link = "GruvboxBlue" },
    CocDiagnosticsHint = { link = "GruvboxAqua" },
    CocSelectedText = { link = "GruvboxRed" },
    CocCodeLens = { link = "GruvboxGray" },
    CocErrorHighlight = { link = "GruvboxRedUnderline" },
    CocWarningHighlight = { link = "GruvboxOrangeUnderline" },
    CocInfoHighlight = { link = "GruvboxBlueUnderline" },
    CocHintHighlight = { link = "GruvboxAquaUnderline" },
    -- ale.vim
    ALEError = { link = "GruvboxRedUnderline" },
    ALEWarning = { link = "GruvboxYellowUnderline" },
    ALEInfo = { link = "GruvboxBlueUnderline" },
    ALEErrorSign = { link = "GruvboxRedSign" },
    ALEWarningSign = { link = "GruvboxYellowSign" },
    ALEInfoSign = { link = "GruvboxBlueSign" },
    ALEVirtualTextError = { link = "GruvboxRed" },
    ALEVirtualTextWarning = { link = "GruvboxYellow" },
    ALEVirtualTextInfo = { link = "GruvboxBlue" },
    -- vim-buftabline
    BufTabLineCurrent = { link = "TabLineSel" },
    BufTabLineActive = { link = "PmenuSel" },
    BufTabLineHidden = { link = "TabLine" },
    BufTabLineFill = { link = "TabLineFill" },
    BufTabLineModifiedCurrent = { link = "BufTabLineCurrent" },
    BufTabLineModifiedActive = { link = "BufTabLineActive" },
    BufTabLineModifiedHidden = { link = "BufTabLineHidden" },
    -- ctrlP
    CtrlPMatch = { link = "Identifier" },
    CtrlPNoEntries = { link = "Error" },
    CtrlPPrtBase = { link = "Comment" },
    CtrlPPrtCursor = { link = "Constant" },
    CtrlPLinePre = { fg = colors.bg2 },
    CtrlPMode1 = { link = "Character" },
    CtrlPMode2 = { link = "LineNr" },
    CtrlPStats = { link = "Function" },
    -- fzf.vim
    Fzf1 = { fg = colors.blue, bg = colors.bg1 },
    Fzf2 = { fg = colors.orange, bg = colors.bg1 },
    Fzf3 = { fg = colors.fg4, bg = colors.bg1 },
    ShowMarksHLl = { link = "GruvboxBlueSign" },
    ShowMarksHLu = { link = "GruvboxBlueSign" },
    ShowMarksHLo = { link = "GruvboxBlueSign" },
    ShowMarksHLm = { link = "GruvboxBlueSign" },
    -- git-gutter
    GitGutterAdd = { link = "GruvboxGreenSign" },
    GitGutterChange = { link = "GruvboxAquaSign" },
    GitGutterDelete = { link = "GruvboxRedSign" },
    GitGutterChangeDelete = { link = "GruvboxAquaSign" },
    -- gitsigns.nvim
    GitSignsAdd = { link = "GruvboxGreenSign" },
    GitSignsChange = { link = "GruvboxOrangeSign" },
    GitSignsDelete = { link = "GruvboxRedSign" },
    GitSignsCurrentLineBlame = { link = "NonText" },
    -- nvim-cmp
    CmpItemAbbr = { link = "GruvboxFg0" },
    CmpItemAbbrDeprecated = { link = "GruvboxFg0" },
    CmpItemAbbrMatch = { link = "GruvboxBlue" },
    CmpItemAbbrMatchFuzzy = { underline = config.underline, fg = colors.aqua },
    CmpItemKind = { link = "GruvboxOrange" },
    CmpItemKindClass = { link = "GruvboxGreen" },
    CmpItemKindConstructor = { link = "GruvboxGreen" },
    CmpItemKindField = { link = "GruvboxAqua" },
    CmpItemKindFile = { link = "GruvboxOrange" },
    CmpItemKindFolder = { link = "GruvboxOrange" },
    CmpItemKindFunction = { link = "GruvboxPurple" },
    CmpItemKindInterface = { link = "GruvboxGreen" },
    CmpItemKindKeyword = { link = "Keyword" },
    CmpItemKindMethod = { link = "GruvboxPurple" },
    CmpItemKindSnippet = { link = "GruvboxYellow" },
    CmpItemKindText = { link = "GruvboxFg0" },
    CmpItemKindValue = { link = "GruvboxOrange" },
    CmpItemKindVariable = { link = "GruvboxBlue" },
    CmpItemMenu = { link = "GruvboxGray" },
    -- LSP
    LspCodeLens = { link = "GruvboxGray" },
    LspReferenceRead = { bg = colors.bg2, underline = config.underline },
    LspReferenceText = { bg = colors.bg2, underline = config.underline },
    LspReferenceWrite = { bg = colors.bg2, underline = config.underline },
    -- Diagnostic
    DiagnosticError = { link = "GruvboxRed" },
    DiagnosticSignError = { link = "GruvboxRedSign" },
    DiagnosticUnderlineError = { link = "GruvboxRedUnderline" },
    DiagnosticWarn = { link = "GruvboxYellow" },
    DiagnosticSignWarn = { link = "GruvboxYellowSign" },
    DiagnosticUnderlineWarn = { link = "GruvboxYellowUnderline" },
    DiagnosticInfo = { link = "GruvboxBlue" },
    DiagnosticSignInfo = { link = "GruvboxBlueSign" },
    DiagnosticUnderlineInfo = { link = "GruvboxBlueUnderline" },
    DiagnosticHint = { link = "GruvboxAqua" },
    DiagnosticSignHint = { link = "GruvboxAquaSign" },
    DiagnosticUnderlineHint = { link = "GruvboxAquaUnderline" },
    DiagnosticFloatingError = { link = "GruvboxRed" },
    DiagnosticFloatingWarn = { link = "GruvboxOrange" },
    DiagnosticFloatingInfo = { link = "GruvboxBlue" },
    DiagnosticFloatingHint = { link = "GruvboxAqua" },
    DiagnosticVirtualTextError = { link = "GruvboxRed" },
    DiagnosticVirtualTextWarn = { link = "GruvboxYellow" },
    DiagnosticVirtualTextInfo = { link = "GruvboxBlue" },
    DiagnosticVirtualTextHint = { link = "GruvboxAqua" },
    -- mail.vim
    mailQuoted1 = { link = "GruvboxAqua" },
    mailQuoted2 = { link = "GruvboxPurple" },
    mailQuoted3 = { link = "GruvboxYellow" },
    mailQuoted4 = { link = "GruvboxGreen" },
    mailQuoted5 = { link = "GruvboxRed" },
    mailQuoted6 = { link = "GruvboxOrange" },
    mailSignature = { link = "Comment" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] and not vim.tbl_isempty(hl) then
      groups[group].link = nil
    end
    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

return M
